version: '3'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - type: bind
        source: "./src"
        target: "/workspace"
    ports:
      - 8080:8000
    depends_on:
      - db

  db:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django_db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      TZ: "Asia/Tokyo"
      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
        - ./mysql/initdb.d:/docker-entrypoint-initdb.d
        - db-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8082:80
    environment:
      - PMA_HOST=db
      - PMA_USER=django
      - PMA_PASSWORD=django

volumes:
  db-volume: